//
//  RestaurantWorker.swift
//  ConnectedColors
//
//  Created by ZhongZhongzhong on 2018-09-21.
//  Copyright (c) 2018 Example. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class UserWorker
{
    var httpService: HTTPServiceProtocol
    
    init(http: HTTPServiceProtocol) {
        self.httpService = http
    }
    
    func getUsers(complete: @escaping UsersCompleteHandler) {
        httpService.getAllUsers(complete: complete)
    }
    
    func getUser(id: String, complete: @escaping UserCompleteHandler) {
        httpService.getCustomerBy(id: id, complete: complete)
    }
    
    func transfer(amount: Int, currency: String, receipt: String, fromAccountID: String, toAccountID: String, complete: @escaping TransferHandler) {
        httpService.transfer(amount: amount, currency: currency, receipt: receipt, fromAccountID: fromAccountID, toAccountID: toAccountID, complete: complete)
    }
}
