//
//  RestaurantPresenter.swift
//  ConnectedColors
//
//  Created by ZhongZhongzhong on 2018-09-21.
//  Copyright (c) 2018 Example. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RestaurantPresentationLogic
{
  func presentSomething(response: Restaurant.Something.Response)
}

class RestaurantPresenter: RestaurantPresentationLogic
{
  weak var viewController: RestaurantDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Restaurant.Something.Response)
  {
    let viewModel = Restaurant.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
