//
//  RestaurantInteractor.swift
//  ConnectedColors
//
//  Created by ZhongZhongzhong on 2018-09-21.
//  Copyright (c) 2018 Example. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RestaurantBusinessLogic
{
  func doSomething(request: Restaurant.Something.Request)
}

protocol RestaurantDataStore
{
  //var name: String { get set }
}

class RestaurantInteractor: RestaurantBusinessLogic, RestaurantDataStore
{
  var presenter: RestaurantPresentationLogic?
  var worker: RestaurantWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Restaurant.Something.Request)
  {
    worker = RestaurantWorker()
    worker?.doSomeWork()
    
    let response = Restaurant.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
