# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConnectedColors' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'ObjectMapper', '~> 3.3'
  pod 'ILLoginKit'
  pod 'JGProgressHUD'
  pod 'ViewAnimator'
  pod 'Eureka', '~> 4.2.0'
  pod 'RAMAnimatedTabBarController'
  pod 'Cosmos', '~> 17.0'
end
